/**
 * Transcript source types
 */
export type TranscriptSource = 'zoom' | 'teams' | 'avoma' | 'manual';

/**
 * Processing status for transcripts
 */
export type ProcessingStatus = 'pending' | 'processing' | 'completed' | 'failed';

/**
 * CRM sync status
 */
export type CRMStatus = 'pending' | 'synced' | 'failed' | 'not_synced';

/**
 * Participant in a call
 */
export interface Participant {
  id: string;
  name: string;
  email?: string;
  role: 'host' | 'participant' | 'rep' | 'prospect';
  company?: string;
}

/**
 * SPICED element with score and content
 */
export interface SPICEDElement {
  key: 'situation' | 'pain' | 'impact' | 'critical_event' | 'expected_decision' | 'decision_criteria';
  label: string;
  content: string;
  score: 1 | 2 | 3 | 4 | 5;
  quotes: string[];
  recommendations?: string[];
}

/**
 * Complete SPICED analysis
 */
export interface SPICEDAnalysis {
  id: string;
  transcriptId: string;
  elements: SPICEDElement[];
  overallScore: number;
  summary: string;
  strengths: string[];
  areasForImprovement: string[];
  coachingFeedback?: string;
  suggestedTasks: SuggestedTask[];
  createdAt: string;
  updatedAt: string;
}

/**
 * Suggested follow-up task
 */
export interface SuggestedTask {
  id: string;
  title: string;
  description: string;
  priority: 'high' | 'medium' | 'low';
  dueDate?: string;
  type: 'follow_up' | 'research' | 'internal' | 'proposal' | 'demo';
  completed: boolean;
  assignedTo?: string;
  crmTaskId?: string;
}

/**
 * Call notes
 */
export interface CallNotes {
  id: string;
  transcriptId: string;
  content: string;
  autoGenerated: boolean;
  editedAt?: string;
  editedBy?: string;
}

/**
 * Full transcript object
 */
export interface Transcript {
  id: string;
  title: string;
  callId?: string;
  rawText: string;
  source: TranscriptSource;
  duration: number; // in seconds
  participants: Participant[];
  status: ProcessingStatus;
  spicedAnalysis?: SPICEDAnalysis;
  callNotes?: CallNotes;
  crmStatus: CRMStatus;
  crmRecordId?: string;
  crmPushedAt?: string;
  avomaId?: string;
  createdAt: string;
  updatedAt: string;
}

/**
 * Transcript list item (lightweight version for list views)
 */
export interface TranscriptListItem {
  id: string;
  title: string;
  source: TranscriptSource;
  duration: number;
  participantCount: number;
  status: ProcessingStatus;
  overallScore?: number;
  crmStatus: CRMStatus;
  createdAt: string;
}

/**
 * Upload transcript request
 */
export interface UploadTranscriptRequest {
  title: string;
  source: TranscriptSource;
  content?: string; // For paste upload
  avomaId?: string; // For Avoma sync
}

/**
 * Upload response
 */
export interface UploadTranscriptResponse {
  id: string;
  status: ProcessingStatus;
  message: string;
}

/**
 * CRM push request
 */
export interface CRMPushRequest {
  transcriptId: string;
  includeNotes: boolean;
  includeTasks: boolean;
  includeAnalysis: boolean;
  dealId?: string;
  contactId?: string;
}

/**
 * CRM push response
 */
export interface CRMPushResponse {
  success: boolean;
  recordId?: string;
  recordUrl?: string;
  error?: string;
}
