'use client';

import { useState, useEffect } from 'react';
import { useParams, useRouter } from 'next/navigation';
import Link from 'next/link';
import {
  ArrowLeft,
  Clock,
  Users,
  Calendar,
  ExternalLink,
  MoreHorizontal,
  Trash2,
  Download,
  AlertCircle,
} from 'lucide-react';
import { Button } from '@/components/common/Button';
import { Card, CardBody } from '@/components/common/Card';
import { Badge } from '@/components/common/Badge';
import { PageLoading } from '@/components/common/LoadingSpinner';
import { Modal, ModalFooter } from '@/components/common/Modal';
import { ProcessingStatus } from '@/components/transcript/ProcessingStatus';
import { TranscriptViewer } from '@/components/transcript/TranscriptViewer';
import { TaskList } from '@/components/transcript/TaskList';
import { CallNotesEditor } from '@/components/transcript/CallNotesEditor';
import { CRMPushButton } from '@/components/transcript/CRMPushButton';
import { SPICEDScores } from '@/components/spiced/SPICEDScores';
import { SPICEDCard } from '@/components/spiced/SPICEDCard';
import { formatDate, formatDuration, cn } from '@/lib/utils';
import { transcriptApi } from '@/lib/api';
import {
  Transcript,
  SPICEDAnalysis,
  CallNotes,
  SuggestedTask,
  CRMPushRequest,
  CRMPushResponse,
  TranscriptSource,
} from '@/lib/types';

const sourceLabels: Record<TranscriptSource, string> = {
  zoom: 'Zoom',
  teams: 'Teams',
  avoma: 'Avoma',
  manual: 'Manual',
};

export default function TranscriptDetailPage() {
  const params = useParams();
  const router = useRouter();
  const transcriptId = params.id as string;

  const [transcript, setTranscript] = useState<Transcript | null>(null);
  const [isLoading, setIsLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [showDeleteModal, setShowDeleteModal] = useState(false);
  const [isDeleting, setIsDeleting] = useState(false);
  const [showActionsMenu, setShowActionsMenu] = useState(false);

  // Load transcript from API
  useEffect(() => {
    loadTranscript();
  }, [transcriptId]);

  const loadTranscript = async () => {
    try {
      setIsLoading(true);
      setError(null);
      const data = await transcriptApi.get(transcriptId);
      setTranscript(data);
    } catch (err) {
      console.error('Failed to load transcript:', err);
      setError(err instanceof Error ? err.message : 'Failed to load transcript');
    } finally {
      setIsLoading(false);
    }
  };

  const handleToggleTask = async (taskId: string, completed: boolean) => {
    if (!transcript?.spicedAnalysis) return;

    try {
      await transcriptApi.toggleTask(transcriptId, taskId, completed);
      // Update local state
      setTranscript((prev) => {
        if (!prev?.spicedAnalysis) return prev;
        return {
          ...prev,
          spicedAnalysis: {
            ...prev.spicedAnalysis,
            suggestedTasks: prev.spicedAnalysis.suggestedTasks.map((task) =>
              task.id === taskId ? { ...task, completed } : task
            ),
          },
        };
      });
    } catch (err) {
      console.error('Failed to toggle task:', err);
    }
  };

  const handleSaveNotes = async (content: string) => {
    try {
      await transcriptApi.updateNotes(transcriptId, content);
      // Update local state
      setTranscript((prev) => {
        if (!prev) return prev;
        return {
          ...prev,
          callNotes: {
            ...(prev.callNotes || { id: 'new', transcriptId: prev.id, autoGenerated: false }),
            content,
            editedAt: new Date().toISOString(),
          },
        };
      });
    } catch (err) {
      console.error('Failed to save notes:', err);
    }
  };

  const handlePushToCRM = async (request: CRMPushRequest): Promise<CRMPushResponse> => {
    try {
      const response = await transcriptApi.pushToCRM(request);
      // Update local state
      setTranscript((prev) => {
        if (!prev) return prev;
        return {
          ...prev,
          crmStatus: 'synced',
          crmRecordId: response.recordId,
          crmPushedAt: new Date().toISOString(),
        };
      });
      return response;
    } catch (err) {
      console.error('Failed to push to CRM:', err);
      throw err;
    }
  };

  const handleDelete = async () => {
    setIsDeleting(true);
    try {
      await transcriptApi.delete(transcriptId);
      router.push('/transcript');
    } catch (err) {
      console.error('Failed to delete transcript:', err);
      setError(err instanceof Error ? err.message : 'Failed to delete transcript');
    } finally {
      setIsDeleting(false);
    }
  };

  if (isLoading) {
    return <PageLoading message="Loading transcript..." />;
  }

  if (error) {
    return (
      <div className="max-w-7xl mx-auto text-center py-12">
        <AlertCircle className="w-12 h-12 text-red-500 mx-auto mb-4" />
        <h2 className="text-xl font-semibold text-neutral-900 mb-2">
          Error loading transcript
        </h2>
        <p className="text-neutral-600 mb-4">{error}</p>
        <div className="flex gap-3 justify-center">
          <Button variant="secondary" onClick={loadTranscript}>
            Try Again
          </Button>
          <Link href="/transcript">
            <Button variant="secondary">Back to Transcripts</Button>
          </Link>
        </div>
      </div>
    );
  }

  if (!transcript) {
    return (
      <div className="max-w-7xl mx-auto text-center py-12">
        <h2 className="text-xl font-semibold text-neutral-900 mb-2">
          Transcript not found
        </h2>
        <p className="text-neutral-600 mb-4">
          The transcript you're looking for doesn't exist or has been deleted.
        </p>
        <Link href="/transcript">
          <Button variant="secondary">Back to Transcripts</Button>
        </Link>
      </div>
    );
  }

  const isProcessing = transcript.status === 'processing' || transcript.status === 'pending';

  return (
    <div className="max-w-7xl mx-auto">
      {/* Header */}
      <div className="flex flex-col lg:flex-row lg:items-center lg:justify-between gap-4 mb-6">
        <div className="flex items-start gap-4">
          <Link
            href="/transcript"
            className="mt-1 p-2 rounded-lg hover:bg-neutral-100 text-neutral-500 transition-colors"
          >
            <ArrowLeft className="w-5 h-5" />
          </Link>
          <div>
            <h1 className="text-2xl font-bold text-neutral-900 mb-1">
              {transcript.title}
            </h1>
            <div className="flex flex-wrap items-center gap-4 text-sm text-neutral-500">
              <span className="flex items-center gap-1">
                <Calendar className="w-4 h-4" />
                {formatDate(transcript.createdAt)}
              </span>
              {transcript.duration && (
                <span className="flex items-center gap-1">
                  <Clock className="w-4 h-4" />
                  {formatDuration(transcript.duration)}
                </span>
              )}
              {transcript.participants && (
                <span className="flex items-center gap-1">
                  <Users className="w-4 h-4" />
                  {transcript.participants.length} participants
                </span>
              )}
              <Badge variant="neutral">{sourceLabels[transcript.source] || 'Manual'}</Badge>
            </div>
          </div>
        </div>

        {/* Actions */}
        <div className="flex items-center gap-3">
          <CRMPushButton
            transcriptId={transcript.id}
            crmStatus={transcript.crmStatus}
            crmRecordUrl={
              transcript.crmRecordId
                ? `https://app.hubspot.com/contacts/123/deal/${transcript.crmRecordId}`
                : undefined
            }
            onPush={handlePushToCRM}
          />

          <div className="relative">
            <Button
              variant="secondary"
              onClick={() => setShowActionsMenu(!showActionsMenu)}
            >
              <MoreHorizontal className="w-4 h-4" />
            </Button>

            {showActionsMenu && (
              <div className="absolute right-0 mt-2 w-48 bg-white rounded-xl border border-neutral-200 shadow-elevated z-50 animate-in">
                <div className="py-1">
                  <button className="flex items-center gap-2 w-full px-4 py-2 text-sm text-neutral-700 hover:bg-neutral-50">
                    <Download className="w-4 h-4" />
                    Export Transcript
                  </button>
                  <hr className="my-1 border-neutral-100" />
                  <button
                    onClick={() => {
                      setShowActionsMenu(false);
                      setShowDeleteModal(true);
                    }}
                    className="flex items-center gap-2 w-full px-4 py-2 text-sm text-danger-600 hover:bg-neutral-50"
                  >
                    <Trash2 className="w-4 h-4" />
                    Delete Transcript
                  </button>
                </div>
              </div>
            )}
          </div>
        </div>
      </div>

      {/* Processing Status */}
      {isProcessing && (
        <ProcessingStatus
          status={transcript.status}
          progress={transcript.status === 'processing' ? 65 : 0}
          estimatedTime={transcript.status === 'processing' ? 45 : undefined}
          className="mb-6"
        />
      )}

      {/* Main Content Grid */}
      {!isProcessing && transcript.spicedAnalysis && (
        <div className="grid lg:grid-cols-3 gap-6">
          {/* Left Column - SPICED Analysis */}
          <div className="lg:col-span-2 space-y-6">
            {/* Overall Scores */}
            <SPICEDScores analysis={transcript.spicedAnalysis} />

            {/* Individual SPICED Cards */}
            <div className="space-y-4">
              <h2 className="text-lg font-semibold text-neutral-900">
                Detailed Analysis
              </h2>
              {transcript.spicedAnalysis.elements?.map((element) => (
                <SPICEDCard key={element.key} element={element} />
              ))}
            </div>

            {/* Transcript Viewer */}
            {transcript.rawText && (
              <TranscriptViewer
                rawText={transcript.rawText}
                duration={transcript.duration || 0}
                participants={transcript.participants || []}
                highlightedQuotes={transcript.spicedAnalysis.elements?.flatMap(
                  (e) => e.quotes || []
                ) || []}
              />
            )}
          </div>

          {/* Right Column - Notes and Tasks */}
          <div className="space-y-6">
            {/* Call Notes */}
            <CallNotesEditor
              notes={transcript.callNotes || null}
              onSave={handleSaveNotes}
            />

            {/* Tasks */}
            {transcript.spicedAnalysis.suggestedTasks && (
              <TaskList
                tasks={transcript.spicedAnalysis.suggestedTasks}
                onToggleTask={handleToggleTask}
              />
            )}
          </div>
        </div>
      )}

      {/* Show raw transcript if no SPICED analysis */}
      {!isProcessing && !transcript.spicedAnalysis && transcript.rawText && (
        <Card>
          <CardBody>
            <h2 className="text-lg font-semibold text-neutral-900 mb-4">
              Transcript
            </h2>
            <pre className="whitespace-pre-wrap text-sm text-neutral-700 font-mono">
              {transcript.rawText}
            </pre>
          </CardBody>
        </Card>
      )}

      {/* Delete Confirmation Modal */}
      <Modal
        isOpen={showDeleteModal}
        onClose={() => setShowDeleteModal(false)}
        title="Delete Transcript"
        size="sm"
      >
        <p className="text-neutral-600">
          Are you sure you want to delete this transcript? This action cannot be
          undone.
        </p>
        <ModalFooter>
          <Button variant="secondary" onClick={() => setShowDeleteModal(false)}>
            Cancel
          </Button>
          <Button
            variant="danger"
            onClick={handleDelete}
            isLoading={isDeleting}
          >
            Delete
          </Button>
        </ModalFooter>
      </Modal>
    </div>
  );
}
