'use client';

import { useState, useEffect, useCallback } from 'react';
import { Save, RotateCcw, Sparkles, Clock } from 'lucide-react';
import { Card, CardHeader, CardTitle, CardBody, CardFooter } from '@/components/common/Card';
import { Button } from '@/components/common/Button';
import { cn, formatDateTime, debounce } from '@/lib/utils';
import { CallNotes } from '@/lib/types';

interface CallNotesEditorProps {
  notes: CallNotes | null;
  onSave: (content: string) => Promise<void>;
  onRegenerate?: () => Promise<void>;
  className?: string;
}

export function CallNotesEditor({
  notes,
  onSave,
  onRegenerate,
  className,
}: CallNotesEditorProps) {
  const [content, setContent] = useState(notes?.content || '');
  const [isSaving, setIsSaving] = useState(false);
  const [isRegenerating, setIsRegenerating] = useState(false);
  const [hasChanges, setHasChanges] = useState(false);
  const [lastSaved, setLastSaved] = useState<Date | null>(null);

  // Update content when notes prop changes
  useEffect(() => {
    if (notes?.content) {
      setContent(notes.content);
      setHasChanges(false);
    }
  }, [notes?.content]);

  // Track changes
  useEffect(() => {
    setHasChanges(content !== (notes?.content || ''));
  }, [content, notes?.content]);

  // Auto-save with debounce
  const debouncedSave = useCallback(
    debounce(async (newContent: string) => {
      if (newContent === notes?.content) return;

      setIsSaving(true);
      try {
        await onSave(newContent);
        setLastSaved(new Date());
        setHasChanges(false);
      } finally {
        setIsSaving(false);
      }
    }, 2000),
    [onSave, notes?.content]
  );

  const handleChange = (e: React.ChangeEvent<HTMLTextAreaElement>) => {
    const newContent = e.target.value;
    setContent(newContent);
    debouncedSave(newContent);
  };

  const handleManualSave = async () => {
    if (!hasChanges) return;

    setIsSaving(true);
    try {
      await onSave(content);
      setLastSaved(new Date());
      setHasChanges(false);
    } finally {
      setIsSaving(false);
    }
  };

  const handleRegenerate = async () => {
    if (!onRegenerate) return;

    const confirmed = window.confirm(
      'This will regenerate the call notes using AI. Any manual edits will be lost. Continue?'
    );
    if (!confirmed) return;

    setIsRegenerating(true);
    try {
      await onRegenerate();
    } finally {
      setIsRegenerating(false);
    }
  };

  const handleReset = () => {
    if (!hasChanges) return;

    const confirmed = window.confirm(
      'Discard your changes and revert to the last saved version?'
    );
    if (confirmed) {
      setContent(notes?.content || '');
      setHasChanges(false);
    }
  };

  return (
    <Card className={className}>
      <CardHeader className="flex flex-row items-center justify-between">
        <div>
          <CardTitle>Call Notes</CardTitle>
          {notes?.autoGenerated && (
            <p className="text-sm text-neutral-500 mt-1 flex items-center gap-1">
              <Sparkles className="w-3 h-3" />
              AI-generated notes
            </p>
          )}
        </div>
        <div className="flex items-center gap-2">
          {hasChanges && (
            <span className="text-xs text-warning-600 font-medium">
              Unsaved changes
            </span>
          )}
          {lastSaved && !hasChanges && (
            <span className="text-xs text-neutral-500 flex items-center gap-1">
              <Clock className="w-3 h-3" />
              Saved {formatDateTime(lastSaved)}
            </span>
          )}
        </div>
      </CardHeader>

      <CardBody>
        <textarea
          value={content}
          onChange={handleChange}
          placeholder="Add call notes here..."
          rows={12}
          className={cn(
            'input resize-none font-normal',
            hasChanges && 'border-warning-300 focus:ring-warning-500 focus:border-warning-500'
          )}
        />
        <p className="helper-text mt-2">
          {content.split(/\s+/).filter(Boolean).length} words
        </p>
      </CardBody>

      <CardFooter className="flex justify-between">
        <div className="flex gap-2">
          {onRegenerate && (
            <Button
              variant="ghost"
              size="sm"
              onClick={handleRegenerate}
              isLoading={isRegenerating}
              leftIcon={<Sparkles className="w-4 h-4" />}
            >
              Regenerate with AI
            </Button>
          )}
        </div>

        <div className="flex gap-2">
          <Button
            variant="secondary"
            size="sm"
            onClick={handleReset}
            disabled={!hasChanges || isSaving}
            leftIcon={<RotateCcw className="w-4 h-4" />}
          >
            Discard
          </Button>
          <Button
            size="sm"
            onClick={handleManualSave}
            isLoading={isSaving}
            disabled={!hasChanges}
            leftIcon={<Save className="w-4 h-4" />}
          >
            Save Notes
          </Button>
        </div>
      </CardFooter>
    </Card>
  );
}
